artifact_uri: file:C:/Users/kpaoi/Porfolio/Automated Model Monitoring & Drift Detection/mlflow_runs/311827224100509265/be2b928e446d48b189a02e53a1d0a05d/artifacts
end_time: 1778296864998
entry_point_name: ''
experiment_id: '311827224100509265'
lifecycle_stage: active
run_id: be2b928e446d48b189a02e53a1d0a05d
run_name: monitoring_week_06
source_name: ''
source_type: 4
source_version: ''
start_time: 1778296864826
status: 3
tags: []
user_id: HP
