artifact_uri: file:C:/Users/kpaoi/Porfolio/Automated Model Monitoring & Drift Detection/mlflow_runs/311827224100509265/e793d829ee6347c19bd13a627aed69f7/artifacts
end_time: 1778296692265
entry_point_name: ''
experiment_id: '311827224100509265'
lifecycle_stage: active
run_id: e793d829ee6347c19bd13a627aed69f7
run_name: baseline_training
source_name: ''
source_type: 4
source_version: ''
start_time: 1778296668471
status: 3
tags: []
user_id: HP
