artifact_uri: file:C:/Users/kpaoi/Porfolio/Automated Model Monitoring & Drift Detection/mlflow_runs/311827224100509265/4023e0ffa040422fafdf431fc61d2bae/artifacts
end_time: 1778296863419
entry_point_name: ''
experiment_id: '311827224100509265'
lifecycle_stage: active
run_id: 4023e0ffa040422fafdf431fc61d2bae
run_name: monitoring_week_03
source_name: ''
source_type: 4
source_version: ''
start_time: 1778296863245
status: 3
tags: []
user_id: HP
